// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lziztfuyzqchorafzqgs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6aXp0ZnV5enFjaG9yYWZ6cWdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc3NDY3MjcsImV4cCI6MjA1MzMyMjcyN30.LKDSkuvuJRT2xwRxKki04CIx1NkXFrz9Wu1_C9VYHkU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);